// Kalā Trail product system: each card answers the traveller’s decision question — why this stop, why now, and what the detour gives back.
import { ArrowUpRight, Clock3, MapPin, Play, Plus, Sparkles, Star } from "lucide-react";
import { motion } from "framer-motion";
import { Link } from "wouter";
import type { CulturalOpportunity } from "../data/opportunities";
import { VirasatDepthSurface } from "./VirasatDepthSurface";
import { CraftEditorialVisual } from "./CraftEditorialVisual";

export function CulturalOpportunityCard({ opportunity, selected, index, onSelect, onAdd, onPreview }: { opportunity: CulturalOpportunity; selected: boolean; index: number; onSelect: (opportunity: CulturalOpportunity) => void; onAdd: (opportunity: CulturalOpportunity) => void; onPreview?: (opportunity: CulturalOpportunity) => void }) {
  const craft = { id: opportunity.craftId, name: opportunity.title, region: opportunity.location.split(",")[0] || "Route discovery", state: opportunity.location.split(",")[1]?.trim() || "India", description: opportunity.summary, category: opportunity.kind, image: opportunity.image, distance: opportunity.distance, detour: opportunity.detour, duration: opportunity.duration, accent: "#b7863d", coordinates: [0, 0] as [number, number] };
  return <VirasatDepthSurface className="opportunity-depth-surface" intensity={3.2}><motion.article className={`opportunity-card ${selected ? "opportunity-card-selected" : ""}`} layout onClick={() => onSelect(opportunity)} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: selected ? -4 : 0, scale: selected ? 1.008 : 1 }} transition={{ delay: index * .06, duration: .35 }}><div className="opportunity-card-media"><CraftEditorialVisual craft={craft} index={index} alt={`${opportunity.title} material study`} /><span>0{index + 1}</span><b>{opportunity.kind}</b></div><div className="opportunity-card-body"><div className="opportunity-card-title"><div><span className="eyebrow">{opportunity.kicker}</span><h3>{opportunity.title}</h3></div><span className="opportunity-rating"><Star size={12} fill="currentColor" />{opportunity.rating}</span></div><p className="opportunity-location"><MapPin size={12} />{opportunity.location}</p><div className="opportunity-proximity"><span>Route relevance</span><strong>{opportunity.distance}</strong><b>{opportunity.detour}</b></div><div className="opportunity-route-meta"><span>{opportunity.duration}</span><i /> <span>{opportunity.availability}</span></div><p className="opportunity-summary">{opportunity.summary}</p><div className="why-stop"><span><Sparkles size={13} />Why stop?</span><p>{opportunity.whyStop}</p></div><div className="opportunity-score"><div><span>Cultural value</span><b>{"★".repeat(opportunity.culturalValue)}<em>{"★".repeat(5 - opportunity.culturalValue)}</em></b></div><div><span>Experience</span><b><Clock3 size={12} />{opportunity.duration.replace(" experience", "")}</b></div><div><span>Popularity</span><b>{opportunity.popularity}%</b></div></div><div className="opportunity-card-footer"><span><strong>₹{opportunity.price}</strong> / person · {opportunity.availability}</span><div><button className="button button-ghost opportunity-preview-button" onClick={(event) => { event.stopPropagation(); (onPreview ?? onSelect)(opportunity); }}><Play size={12} fill="currentColor" />Preview</button><Link href={opportunity.id === "channapatna-maker-studio" ? "/maker/artisan-studio" : `/craft/${opportunity.craftId}`} className="button button-ghost">Explore <ArrowUpRight size={13} /></Link><button className="button button-primary" onClick={(event) => { event.stopPropagation(); onAdd(opportunity); }}><Plus size={13} />Add to trail</button></div></div></div></motion.article></VirasatDepthSurface>;
}
