// Kalā Trail visual system: Museum in Motion — recognisable Indian craft forms suspended in a warm, atmospheric gallery.
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";

type Vec3 = [number, number, number];

function useCompactScene() {
  const [compact, setCompact] = useState(false);
  useEffect(() => { const update = () => setCompact(window.innerWidth < 760); update(); window.addEventListener("resize", update); return () => window.removeEventListener("resize", update); }, []);
  return compact;
}

function useMotionPreferences() {
  const [reduced, setReduced] = useState(false);
  useEffect(() => { const media = window.matchMedia("(prefers-reduced-motion: reduce)"); const update = () => setReduced(media.matches); update(); media.addEventListener("change", update); return () => media.removeEventListener("change", update); }, []);
  return reduced;
}

function FloatPath({ children, base, depth = 1, speed = 0.18, phase = 0, tilt = 0.08, reduced = false }: { children: React.ReactNode; base: Vec3; depth?: number; speed?: number; phase?: number; tilt?: number; reduced?: boolean }) {
  const group = useRef<THREE.Group>(null); const target = useRef(new THREE.Vector3()); const { pointer } = useThree();
  useFrame(({ clock }) => { if (!group.current) return; const time = clock.getElapsedTime() * speed + phase; const motion = reduced ? 0 : 1; target.current.set(base[0] + Math.sin(time * 1.18) * .13 * motion + pointer.x * depth * .08 * motion, base[1] + Math.cos(time * 1.35) * .15 * motion + pointer.y * depth * .07 * motion, base[2] + Math.sin(time * .7) * .07 * motion); group.current.position.lerp(target.current, reduced ? 1 : .035); group.current.rotation.x = THREE.MathUtils.lerp(group.current.rotation.x, Math.sin(time * .7) * tilt * motion + pointer.y * depth * .025 * motion, reduced ? 1 : .035); group.current.rotation.y = THREE.MathUtils.lerp(group.current.rotation.y, Math.sin(time * .48) * (tilt * 1.8) * motion + pointer.x * depth * .07 * motion, reduced ? 1 : .035); });
  return <group ref={group}>{children}</group>;
}

function LatheVessel({ position = [0, 0, 0], scale = 1, color = "#a95f43", glaze = false }: { position?: Vec3; scale?: number; color?: string; glaze?: boolean }) {
  const profile = useMemo(() => [new THREE.Vector2(.1, -.62), new THREE.Vector2(.25, -.58), new THREE.Vector2(.42, -.31), new THREE.Vector2(.47, -.04), new THREE.Vector2(.4, .3), new THREE.Vector2(.25, .54), new THREE.Vector2(.2, .57), new THREE.Vector2(.18, .61)], []);
  return <group position={position} scale={scale} castShadow><mesh castShadow receiveShadow><latheGeometry args={[profile, 48]} /><meshStandardMaterial color={color} roughness={glaze ? .32 : .66} metalness={glaze ? .08 : .02} /></mesh><mesh position={[0, .6, 0]} scale={[1, .28, 1]}><torusGeometry args={[.19, .038, 10, 40]} /><meshStandardMaterial color={glaze ? "#75483b" : "#814c3d"} roughness={.45} /></mesh><mesh position={[0, -.47, 0]} scale={[1, .12, 1]}><torusGeometry args={[.29, .016, 8, 40]} /><meshStandardMaterial color="#d49a6d" roughness={.62} /></mesh></group>;
}

function Diya({ position = [0, 0, 0], scale = 1 }: { position?: Vec3; scale?: number }) {
  const bowl = useMemo(() => [new THREE.Vector2(.1, -.24), new THREE.Vector2(.31, -.2), new THREE.Vector2(.52, -.06), new THREE.Vector2(.57, .06), new THREE.Vector2(.54, .12), new THREE.Vector2(.25, .19)], []);
  return <group position={position} scale={scale} rotation={[.12, -.32, 0]}><mesh castShadow><latheGeometry args={[bowl, 48]} /><meshStandardMaterial color="#b86343" roughness={.44} metalness={.03} /></mesh><mesh position={[0, .15, 0]} scale={[1, .25, 1]}><torusGeometry args={[.27, .025, 10, 40]} /><meshStandardMaterial color="#7d4235" roughness={.48} /></mesh><mesh position={[.03, .28, 0]} rotation={[0, 0, -.18]}><cylinderGeometry args={[.03, .045, .25, 10]} /><meshStandardMaterial color="#3c2b20" roughness={.9} /></mesh><mesh position={[.02, .46, 0]} scale={[.5, 1.1, .5]}><sphereGeometry args={[.11, 18, 14]} /><meshStandardMaterial color="#e8b75f" emissive="#d58438" emissiveIntensity={.35} roughness={.3} /></mesh><pointLight position={[0, .58, .25]} intensity={.8} color="#ffd08a" distance={2.1} /></group>;
}

function ChannapatnaToy({ position = [0, 0, 0], scale = 1, highlighted = false, reduced = false }: { position?: Vec3; scale?: number; highlighted?: boolean; reduced?: boolean }) {
  const group = useRef<THREE.Group>(null); const [hovered, setHovered] = useState(false); useFrame(({ clock }) => { if (group.current) group.current.rotation.y = reduced ? 0 : Math.sin(clock.getElapsedTime() * .18) * .16; });
  const lacquer = highlighted || hovered ? "#d77c55" : "#bd6747"; const trunkCurve = useMemo(() => new THREE.CatmullRomCurve3([new THREE.Vector3(.76, .23, 0), new THREE.Vector3(.98, .07, 0), new THREE.Vector3(.92, -.22, 0), new THREE.Vector3(.72, -.27, 0)]), []);
  return <group ref={group} position={position} scale={scale} rotation={[.04, -.35, 0]} onPointerOver={() => setHovered(true)} onPointerOut={() => setHovered(false)}><mesh castShadow position={[0, .02, 0]} scale={[1.02, .5, .44]}><sphereGeometry args={[.68, 36, 24]} /><meshStandardMaterial color={lacquer} roughness={.27} metalness={.08} /></mesh><mesh castShadow position={[.52, .31, 0]} scale={[.42, .5, .37]}><sphereGeometry args={[.5, 32, 24]} /><meshStandardMaterial color="#d9a24f" roughness={.3} /></mesh><mesh castShadow position={[.53, .39, .3]} scale={[.32, .42, .09]}><sphereGeometry args={[.5, 28, 20]} /><meshStandardMaterial color="#385a4d" roughness={.42} /></mesh><mesh castShadow position={[.53, .39, -.3]} scale={[.32, .42, .09]}><sphereGeometry args={[.5, 28, 20]} /><meshStandardMaterial color="#385a4d" roughness={.42} /></mesh><mesh castShadow position={[.78, .56, 0]} scale={[.16, .3, .14]} rotation={[0, 0, -.28]}><coneGeometry args={[.22, .58, 22]} /><meshStandardMaterial color="#e9bf61" roughness={.34} /></mesh><mesh castShadow position={[.43, .58, 0]} scale={[.14, .27, .13]} rotation={[0, 0, .2]}><coneGeometry args={[.22, .53, 22]} /><meshStandardMaterial color="#e9bf61" roughness={.34} /></mesh><mesh castShadow><tubeGeometry args={[trunkCurve, 28, .06, 10, false]} /><meshStandardMaterial color="#d9a24f" roughness={.3} /></mesh><mesh position={[-.18, .03, .42]} rotation={[Math.PI / 2, 0, 0]}><torusGeometry args={[.29, .035, 10, 32]} /><meshStandardMaterial color="#f1c769" roughness={.24} metalness={.18} /></mesh><mesh position={[-.1, .02, 0]} rotation={[0, 0, Math.PI / 2]} scale={[1, 1, .48]}><torusGeometry args={[.52, .04, 10, 36]} /><meshStandardMaterial color="#f0c268" roughness={.25} metalness={.13} /></mesh>{[[-.47, -.4, .24], [.45, -.4, .24], [-.47, -.4, -.24], [.45, -.4, -.24]].map((wheel, index) => <mesh key={index} position={wheel as Vec3} rotation={[Math.PI / 2, 0, 0]} castShadow><cylinderGeometry args={[.22, .22, .12, 28]} /><meshStandardMaterial color="#25493f" roughness={.38} /></mesh>)}<mesh position={[.69, .31, .32]} scale={[.08, .08, .05]}><sphereGeometry args={[1, 16, 12]} /><meshStandardMaterial color="#1d2724" roughness={.2} /></mesh><mesh position={[.69, .31, -.32]} scale={[.08, .08, .05]}><sphereGeometry args={[1, 16, 12]} /><meshStandardMaterial color="#1d2724" roughness={.2} /></mesh><mesh position={[-.76, .08, 0]} rotation={[0, 0, -.95]}><coneGeometry args={[.08, .35, 12]} /><meshStandardMaterial color="#385a4d" roughness={.52} /></mesh></group>;
}

function ThreadSpool({ position = [0, 0, 0], scale = 1 }: { position?: Vec3; scale?: number }) { return <group position={position} scale={scale} rotation={[.5, .28, -.36]}><mesh castShadow><cylinderGeometry args={[.31, .31, .68, 40]} /><meshStandardMaterial color="#c99549" roughness={.3} metalness={.08} /></mesh>{[-.24, -.12, 0, .12, .24].map((y) => <mesh key={y} position={[0, y, 0]} rotation={[0, 0, Math.PI / 2]}><torusGeometry args={[.317, .012, 8, 36]} /><meshStandardMaterial color="#dcb362" roughness={.25} /></mesh>)}<mesh position={[0, .37, 0]}><cylinderGeometry args={[.17, .17, .08, 24]} /><meshStandardMaterial color="#8a563e" roughness={.58} /></mesh><mesh position={[0, -.37, 0]}><cylinderGeometry args={[.17, .17, .08, 24]} /><meshStandardMaterial color="#8a563e" roughness={.58} /></mesh></group>; }
function CarvedFinial({ position = [0, 0, 0], scale = 1 }: { position?: Vec3; scale?: number }) { return <group position={position} scale={scale} rotation={[.08, .35, 0]}><mesh castShadow position={[0, -.36, 0]}><cylinderGeometry args={[.38, .42, .18, 32]} /><meshStandardMaterial color="#6e4633" roughness={.58} /></mesh><mesh castShadow position={[0, -.12, 0]}><sphereGeometry args={[.33, 32, 24]} /><meshStandardMaterial color="#87543a" roughness={.48} /></mesh><mesh castShadow position={[0, .3, 0]}><coneGeometry args={[.28, .62, 32]} /><meshStandardMaterial color="#9b6341" roughness={.47} /></mesh><mesh position={[0, -.12, 0]} scale={[1, .34, 1]}><torusGeometry args={[.34, .03, 10, 36]} /><meshStandardMaterial color="#d2a35c" roughness={.32} metalness={.12} /></mesh></group>; }

function CraftAtmosphere({ compact, reduced }: { compact: boolean; reduced: boolean }) { const group = useRef<THREE.Points>(null); const points = useMemo(() => { const count = compact ? 18 : 54; const values = new Float32Array(count * 3); let seed = 91; const next = () => { seed = (seed * 16807) % 2147483647; return (seed - 1) / 2147483646; }; for (let i = 0; i < count; i += 1) { values[i * 3] = (next() - .5) * 8.5; values[i * 3 + 1] = (next() - .5) * 4.2; values[i * 3 + 2] = -1.7 + next() * 2.4; } return values; }, [compact]); useFrame(({ clock }) => { if (group.current && !reduced) { group.current.rotation.z = Math.sin(clock.getElapsedTime() * .05) * .04; group.current.position.y = Math.sin(clock.getElapsedTime() * .09) * .05; } }); return <points ref={group}><bufferGeometry><bufferAttribute attach="attributes-position" args={[points, 3]} /></bufferGeometry><pointsMaterial color="#d9b15d" size={compact ? .024 : .032} transparent opacity={.28} depthWrite={false} sizeAttenuation /></points>; }

function GalleryScene({ focus, compact, reduced }: { focus: boolean; compact: boolean; reduced: boolean }) { return <><color attach="background" args={[focus ? "#e9dece" : "#173e37"]} /><hemisphereLight intensity={1.6} color="#fff0d5" groundColor="#34564a" /><directionalLight position={[4.5, 6, 5]} intensity={3.4} color="#fff1d3" castShadow shadow-mapSize-width={512} shadow-mapSize-height={512} /><pointLight position={[-4, 1, 1]} intensity={1.3} color="#c97b59" distance={7} /><pointLight position={[2, -1, 3]} intensity={.75} color="#d9b35f" distance={5} />{focus ? <FloatPath base={[0, 0, 0]} depth={.65} speed={.2} phase={.2} tilt={.04} reduced={reduced}><ChannapatnaToy scale={1.28} highlighted reduced={reduced} /></FloatPath> : <><FloatPath base={[-2.9, 1.08, .55]} depth={.45} speed={.16} phase={.1} reduced={reduced}><Diya scale={.9} /></FloatPath><FloatPath base={[1.95, .5, .15]} depth={.95} speed={.2} phase={1.9} tilt={.06} reduced={reduced}><ChannapatnaToy scale={1} reduced={reduced} /></FloatPath><FloatPath base={[-1.22, -1.17, -.5]} depth={.28} speed={.14} phase={2.6} reduced={reduced}><LatheVessel scale={.9} /></FloatPath>{!compact && <FloatPath base={[3.05, -.82, .46]} depth={.55} speed={.23} phase={3.4} reduced={reduced}><ThreadSpool scale={.95} /></FloatPath>}{!compact && <FloatPath base={[-3.52, -.48, -.82]} depth={.15} speed={.12} phase={4.8} reduced={reduced}><CarvedFinial scale={.8} /></FloatPath>}</>} {!focus && <CraftAtmosphere compact={compact} reduced={reduced} />}<mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -1.72, 0]} receiveShadow><planeGeometry args={[15, 12]} /><shadowMaterial color="#0d2f2a" opacity={focus ? .13 : .18} /></mesh></>; }

export function ThreeCraftStage({ focus = false, className = "" }: { focus?: boolean; className?: string }) { const compact = useCompactScene(); const reduced = useMotionPreferences(); return <div className={`craft-stage ${className}`} aria-label={focus ? "Slowly rotating Channapatna-inspired lacquered wooden toy" : "Floating Indian craft objects: a diya, Channapatna toy, pottery vessel, carved wood finial, and textile spool"}><Canvas shadows frameloop={reduced ? "demand" : "always"} dpr={compact ? [1, 1.15] : [1, 1.6]} camera={{ position: focus ? [0, 0, 5.5] : [0, 0, 6.6], fov: focus ? 34 : 36 }} gl={{ antialias: !compact, powerPreference: "high-performance" }}><GalleryScene focus={focus} compact={compact} reduced={reduced} /></Canvas></div>; }
