// Virāsat route service: FastAPI is always attempted first; normalization and a labelled local fallback keep the heritage UI stable for demos.
import type { Craft } from "../data/mock";
import type { CulturalOpportunity } from "../data/opportunities";
import { buildRouteExperience, resolveIndiaLocation, type RouteExperience } from "../data/routeDiscovery";
import { apiRequest, API_BASE_URL, ROUTE_REQUEST_TIMEOUT_MS } from "./api";
import { getHeritageKicker, overlayCraftHeritage } from "./heritageEnrichmentService";

type BackendCraft = { id: number; name: string; category?: string | null; state?: string | null; district?: string | null; description?: string | null; ai_description?: string | null; lat?: number | null; lng?: number | null; image_url?: string | null; distance_from_route_km?: number; };
type BackendRouteResponse = { route_point_count: number; crafts_found: number; crafts: BackendCraft[]; trip_summary?: string | null };
export type RouteDiscoveryResult = { experience: RouteExperience; source: "api" | "mock"; endpoint: string; tripSummary?: string | null; fallbackReason?: string };
const imageFor = (craft: BackendCraft) => craft.image_url || (craft.category?.toLowerCase().includes("textile") ? "/manus-storage/virasat-craft-weaving_76580db7.jpg" : craft.category?.toLowerCase().includes("metal") ? "/manus-storage/virasat-craft-metalwork_f249c877.jpg" : "/manus-storage/virasat-craft-terracotta_b9573ecd.jpg");
const normalizeCraft = (craft: BackendCraft, index: number): Craft => overlayCraftHeritage({ id: `api-${craft.id}`, name: craft.name, region: craft.district || craft.state || "Regional craft", state: craft.state || "India", description: craft.ai_description || craft.description || "A living craft practice discovered along your journey.", category: craft.category || "Craft tradition", gi: false, image: imageFor(craft), distance: typeof craft.distance_from_route_km === "number" ? `${craft.distance_from_route_km.toFixed(1)} km from route` : "Near your route", detour: `+${10 + index * 7} min detour`, duration: `${45 + index * 15} min maker visit`, accent: ["#b96745", "#967943", "#35564c"][index % 3], coordinates: [Number(craft.lat) || 20 + index, Number(craft.lng) || 78 + index] });
const opportunityFor = (craft: Craft, index: number, origin: string, destination: string): CulturalOpportunity => ({ id: `api-route-${craft.id}`, craftId: craft.id, title: craft.name, kicker: getHeritageKicker(craft.id, "Live route discovery"), kind: index === 0 ? "Craft" : index === 1 ? "Artisan" : "Experience", location: `${craft.region}, ${craft.state}`, image: craft.image, distance: craft.distance, detour: craft.detour, duration: craft.duration, price: 250 + index * 100, rating: Number((4.9 - index * .1).toFixed(1)), popularity: 92 - index * 7, culturalValue: Math.max(3, 5 - index), summary: craft.description, whyStop: `${craft.region} was traced from the live craft dataset as a meaningful discovery between ${origin} and ${destination}.`, availability: index === 0 ? "Live craft record" : "Route discovery", icon: index === 0 ? "✦" : index === 1 ? "⌁" : "◌" });
function normalizeRoute(originInput: string, destinationInput: string, response: BackendRouteResponse): RouteExperience | null { const origin = resolveIndiaLocation(originInput); const destination = resolveIndiaLocation(destinationInput); if (!origin || !destination) return null; const crafts = response.crafts.map(normalizeCraft); const midpoint: [number, number] = [(origin.coordinates[0] + destination.coordinates[0]) / 2, (origin.coordinates[1] + destination.coordinates[1]) / 2]; return { origin, destination, crafts, opportunities: crafts.map((craft, index) => opportunityFor(craft, index, origin.name, destination.name)), path: [origin.coordinates, ...crafts.map((craft) => craft.coordinates), destination.coordinates], distance: `${response.route_point_count.toLocaleString("en-IN")} route points`, duration: "Live route trace", regionLabel: `${origin.state} · ${destination.state}`, heritageCoordinates: midpoint }; }
export async function discoverRoute(originInput: string, destinationInput: string): Promise<RouteDiscoveryResult> { const origin = resolveIndiaLocation(originInput); const destination = resolveIndiaLocation(destinationInput); if (!origin || !destination || origin.id === destination.id) throw new Error("Choose two different supported Indian locations to trace a route."); const payload = { start_lat: origin.coordinates[0], start_lng: origin.coordinates[1], end_lat: destination.coordinates[0], end_lng: destination.coordinates[1], buffer_km: 50, start_label: origin.name, end_label: destination.name, include_summary: true }; try { const response = await apiRequest<BackendRouteResponse>("/trip/crafts-along-route", { method: "POST", body: JSON.stringify(payload) }, ROUTE_REQUEST_TIMEOUT_MS); const experience = normalizeRoute(originInput, destinationInput, response); if (!experience) throw new Error("The route response could not be mapped to this journey."); return { experience, source: "api", endpoint: `${API_BASE_URL}/trip/crafts-along-route`, tripSummary: response.trip_summary ?? null }; } catch (error) { const fallback = buildRouteExperience(originInput, destinationInput); if (!fallback) throw error; return { experience: fallback, source: "mock", endpoint: `${API_BASE_URL}/trip/crafts-along-route`, fallbackReason: error instanceof Error ? error.message : "The live route service is unavailable." }; } }
