// Virāsat landing visual system: exactly three hand-crafted materials form a balanced contemporary museum installation — earth, textile, and wood.
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";

type ArtifactLabel = "01 · TEXTILE" | "02 · POTTERY" | "03 · WOODCRAFT" | null;
type Vec3 = [number, number, number];

function useReducedMotion() { const [reduced, setReduced] = useState(false); useEffect(() => { const media = window.matchMedia("(prefers-reduced-motion: reduce)"); const update = () => setReduced(media.matches); update(); media.addEventListener("change", update); return () => media.removeEventListener("change", update); }, []); return reduced; }
function ArtifactMotion({ base, depth, label, onLabel, children }: { base: Vec3; depth: number; label: Exclude<ArtifactLabel, null>; onLabel: (label: ArtifactLabel) => void; children: React.ReactNode }) { const group = useRef<THREE.Group>(null); const { pointer } = useThree(); const reduced = useReducedMotion(); useFrame(({ clock }) => { if (!group.current) return; const time = clock.getElapsedTime(); const px = reduced ? 0 : pointer.x; const py = reduced ? 0 : pointer.y; group.current.position.x = THREE.MathUtils.lerp(group.current.position.x, base[0] + px * depth * .19, .03); group.current.position.y = THREE.MathUtils.lerp(group.current.position.y, base[1] + py * depth * .12 + Math.sin(time * .22 + depth) * .025, .03); group.current.position.z = base[2]; group.current.rotation.y = THREE.MathUtils.lerp(group.current.rotation.y, px * depth * .09 + Math.sin(time * .12 + depth) * .045, .028); }); return <group ref={group} onPointerOver={(event) => { event.stopPropagation(); onLabel(label); }} onPointerOut={() => onLabel(null)}>{children}</group>; }
function Dust({ compact }: { compact: boolean }) { const positions = useMemo(() => { const count = compact ? 18 : 30; const array = new Float32Array(count * 3); for (let i = 0; i < count; i++) { array[i * 3] = (Math.random() - .5) * 6; array[i * 3 + 1] = (Math.random() - .5) * 4.5; array[i * 3 + 2] = (Math.random() - .5) * 1.5 - .5; } return array; }, [compact]); const points = useRef<THREE.Points>(null); const reduced = useReducedMotion(); useFrame(({ clock }) => { if (points.current && !reduced) points.current.rotation.y = Math.sin(clock.getElapsedTime() * .03) * .035; }); return <points ref={points}><bufferGeometry><bufferAttribute attach="attributes-position" args={[positions, 3]} /></bufferGeometry><pointsMaterial color="#c89e57" size={.022} sizeAttenuation transparent opacity={.42} depthWrite={false} /></points>; }
function Diya() { const profile = useMemo(() => [new THREE.Vector2(.07,-.25),new THREE.Vector2(.34,-.22),new THREE.Vector2(.56,-.08),new THREE.Vector2(.59,.06),new THREE.Vector2(.48,.17),new THREE.Vector2(.22,.21)], []); return <group rotation={[.1,-.3,0]} scale={.94}><mesh castShadow><latheGeometry args={[profile, 48]} /><meshStandardMaterial color="#a9583e" roughness={.66} metalness={.02} /></mesh><mesh position={[0,.18,0]} scale={[1,.24,1]}><torusGeometry args={[.31,.025,10,40]} /><meshStandardMaterial color="#713c30" roughness={.56} /></mesh><mesh position={[.01,.34,0]} rotation={[0,0,-.16]}><cylinderGeometry args={[.026,.045,.25,10]} /><meshStandardMaterial color="#312218" roughness={.9} /></mesh><mesh position={[0,.51,0]} scale={[.46,1,.46]}><sphereGeometry args={[.11,18,14]} /><meshStandardMaterial color="#d9a352" emissive="#af6a2e" emissiveIntensity={.22} roughness={.42} /></mesh></group>; }
function Textile() { const folds = useMemo(() => [-.1,0,.1].map((offset) => new THREE.CatmullRomCurve3([new THREE.Vector3(-.31,offset,0),new THREE.Vector3(.03,.19 + offset,.06),new THREE.Vector3(.4,.1 + offset,-.03),new THREE.Vector3(.72,.29 + offset,.03)])), []); const ribbon = useRef<THREE.Group>(null); const reduced = useReducedMotion(); useFrame(({ clock }) => { if (ribbon.current && !reduced) { ribbon.current.rotation.z = Math.sin(clock.getElapsedTime() * .18) * .035 - .1; ribbon.current.position.y = Math.sin(clock.getElapsedTime() * .22) * .02; } }); return <group ref={ribbon} rotation={[.12,.28,-.1]}><mesh castShadow position={[-.43,0,0]} rotation={[Math.PI / 2,0,.12]}><cylinderGeometry args={[.16,.16,.56,32]} /><meshStandardMaterial color="#ae8548" roughness={.36} metalness={.08} /></mesh>{[-.16,-.06,.05,.16].map((x) => <mesh key={x} position={[-.43,x,0]} rotation={[Math.PI / 2,0,.12]}><torusGeometry args={[.164,.009,8,32]} /><meshStandardMaterial color="#d9b76a" roughness={.28} /></mesh>)}{folds.map((curve, index) => <mesh key={index} castShadow><tubeGeometry args={[curve,32,.055,8,false]} /><meshStandardMaterial color={index === 1 ? "#bd754f" : "#a86646"} roughness={.54} metalness={.02} /></mesh>)}</group>; }
function Woodcraft() { return <group rotation={[.08,.34,.04]} scale={.95}><mesh castShadow position={[0,-.36,0]}><cylinderGeometry args={[.36,.42,.18,32]} /><meshStandardMaterial color="#69412e" roughness={.7} /></mesh><mesh castShadow position={[0,-.1,0]}><sphereGeometry args={[.31,32,24]} /><meshStandardMaterial color="#875239" roughness={.56} /></mesh><mesh castShadow position={[0,.31,0]}><coneGeometry args={[.27,.64,32]} /><meshStandardMaterial color="#9b6744" roughness={.54} /></mesh><mesh position={[0,-.1,0]} scale={[1,.34,1]}><torusGeometry args={[.33,.026,10,36]} /><meshStandardMaterial color="#c49152" roughness={.37} metalness={.08} /></mesh><mesh position={[0,.16,0]} scale={[1,.36,1]}><torusGeometry args={[.25,.02,10,36]} /><meshStandardMaterial color="#d0a862" roughness={.38} /></mesh></group>; }
function MuseumScene({ onLabel, compact }: { onLabel: (label: ArtifactLabel) => void; compact: boolean }) { return <><ambientLight intensity={1.16} color="#ead7b0" /><directionalLight position={[3.8,5,4]} intensity={2.8} color="#ffe4b7" castShadow /><pointLight position={[-3,1.2,2]} intensity={.9} color="#b66142" distance={6} /><pointLight position={[1,1.6,1]} intensity={.55} color="#c79a50" distance={4} /><Dust compact={compact} /><ArtifactMotion base={[-1.24,-.78,.3]} depth={.95} label="02 · POTTERY" onLabel={onLabel}><Diya /></ArtifactMotion><ArtifactMotion base={[.2,1.04,-.5]} depth={.35} label="01 · TEXTILE" onLabel={onLabel}><Textile /></ArtifactMotion><ArtifactMotion base={[1.25,-.55,.62]} depth={.62} label="03 · WOODCRAFT" onLabel={onLabel}><Woodcraft /></ArtifactMotion><mesh rotation={[-Math.PI / 2,0,0]} position={[0,-1.38,0]} receiveShadow><planeGeometry args={[8,6]} /><shadowMaterial color="#061914" opacity={.34} /></mesh></>; }
export function VirasatStage({ onArtifactChange }: { onArtifactChange?: (label: ArtifactLabel) => void }) { const [compact, setCompact] = useState(false); useEffect(() => { const update = () => setCompact(window.innerWidth < 700); update(); window.addEventListener("resize", update); return () => window.removeEventListener("resize", update); }, []); return <div className="virasat-stage" aria-label="A balanced installation of three Indian heritage artifacts: terracotta pottery, woven textile, and carved woodcraft"><Canvas shadows dpr={compact ? [1,1.2] : [1,1.45]} camera={{ position: [0,.05,5.7], fov: 36 }} gl={{ alpha: true, antialias: !compact, powerPreference: "high-performance" }} onPointerMissed={() => onArtifactChange?.(null)}><MuseumScene compact={compact} onLabel={(label) => onArtifactChange?.(label)} /></Canvas></div>; }
